### ISSUE TITLE
Doc Wrong

### ISSUE THREAD

**Issue by Wu-Jiayang** [abersheeran/kui#71]
doc link: https://kui.aber.sh/zh/asgi/http/#streamresponse

![image](https://github.com/user-attachments/assets/85072058-2107-4c2b-b892-41b120f6903f)

TypeError: bytes object expected; got str

**Comment by Wu-Jiayang** [comment]
```python
import asyncio
from kui.asgi import StreamResponse, Kui, HttpView, MultimethodRoutes


router = MultimethodRoutes(base_class=HttpView)

async def slow_numbers(minimum, maximum):
    yield('<html><body><ul>')
    for number in range(minimum, maximum + 1):
        yield '<li>%d</li>' % number
        await asyncio.sleep(0.5)
    yield('</ul></body></html>')


@router.http.get("/")
async def return_stream():
    generator = slow_numbers(1, 10)
    return StreamResponse(generator, content_type='text/html')


if __name__ == '__main__':
    import uvicorn

    app = Kui(
        routes=[router],
    )
    uvicorn.run(app, host="0.0.0.0", port=9000)
```
```sh
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\py\insurance-agent\.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\py\insurance-agent\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
INFO:     127.0.0.1:11499 - "GET / HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\py\insurance-agent\.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\py\insurance-agent\.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\py\insurance-agent\.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\py\insurance-agent\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    result = await app(  # type: ignore[func-returns-value]
  File "D:\py\insurance-agent\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
  File "D:\py\insurance-agent\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\py\insurance-agent\.venv\lib\site-packages\kui\asgi\applications.py", line 163, in __call__
    await self.app(scope, receive, send)
  File "D:\py\insurance-agent\.venv\lib\site-packages\kui\asgi\applications.py", line 118, in app
    return await getattr(self, scope_type)(scope, receive, send)
  File "D:\py\insurance-agent\.venv\lib\site-packages\kui\asgi\applications.py", line 142, in http
    return await response(scope, receive, send)
  File "D:\py\insurance-agent\.venv\lib\site-packages\baize\asgi\responses.py", line 155, in __call__
    await send_http_body(send, chunk, more_body=True)
  File "baize\asgi\helper.py", line 22, in send_http_body
TypeError: bytes object expected; got str
```

**Comment by abersheeran** [comment]
Thank you
